### ISSUE TITLE
Mouse position is incorrect unless at 90 degree angles

### ISSUE THREAD

**Issue by MattJeanes** [HandsomeMatt/3d2d-vgui#5]
Basically the code that converts the mouse position to screen position in 3D space only seems to work at 90 degree angles, or else it starts to slip and go wrong:

http://i.imgur.com/n4JQRlK.gifv

I also edited the code a bit to give a helper + symbol where the mouse thinks it is

**Comment by MattJeanes** [comment]
Issue appears to be somewhere in here:

https://github.com/HandsomeMatt/3d2d-vgui/blob/master/3d2dvgui.lua#L41-L46

What's strange is that the height is fine, but the width isn't. Also seems independent of aspect ratio, even 1:1 (square).

I made another gif to show the issue more clearly, the number displayed is the yaw angle, the (non moving) crosshair is the mouse's actual position, and the two intersecting lines show where the screen thinks the mouse is.

Note how it approaches the correct position at 0 and -90, right angles. I'm really shit at maths so I don't really know what's causing it - and can't think of a way to fix it, @HandsomeMatt pls

![](http://i.imgur.com/rlFu3ck.gif)

**Comment by HandsomeMatt** [comment]
think I got it, will commit asap https://dl.dropboxusercontent.com/u/3659637/2015-05-16_01-13-30.webm

**Comment by MattJeanes** [comment]
thanks babe
