### ISSUE TITLE
gui.MouseX & gui.MouseY fucked up

### ISSUE THREAD

**Issue by robotboy655** [HandsomeMatt/3d2d-vgui#6]
Having this installed fucks up gui.MouseX and gui.MouseY for all other addons:
https://github.com/HandsomeMatt/3d2d-vgui/blob/master/3d2dvgui.lua#L88-L95

You probably should fall back to ```x, y = gui.MousePos()``` if x and y are 'nan'
https://github.com/HandsomeMatt/3d2d-vgui/blob/master/3d2dvgui.lua#L48

**Comment by MattJeanes** [comment]
I disabled this in my version since I noticed the same thing, but it doesn't really appear to do anything anyway?

**Comment by robotboy655** [comment]
It fucks up every DermaMenu() for one. That's how I noticed this shit and messing around with 3d2d vgui

**Comment by HandsomeMatt** [comment]
I think this was a hack for some weird stuff VGUI used to do, I'll change it so it doesn't use it.
