### ISSUE TITLE
DPropertySheet not detecting the click on the right tab

### ISSUE THREAD

**Issue by ExtReMLapin** [HandsomeMatt/3d2d-vgui#9]
TL;DR : Video with debugs instructions (I mean Lua instruction, so Lua code)

https://www.youtube.com/watch?v=M3GgOIgpm10

Sorry for baguette accent

Some times (yes, you have to try about 6 time to make it work), when switching between tabs, the function postPanelEvent, will not call the mouse even on the right tab.

The non 3d2d version of my derma works great.

**Comment by MattJeanes** [comment]
This is most likely related to Z-ordering while trying to find the button that the user is looking at. AFAIK there is no method to find which element is on top so it sorta guesses. I've looked at the issue but was unable to find a fix for it. @HandsomeMatt may however be able to.

**Comment by ExtReMLapin** [comment]
The Menu looks right (the visual part).

The "hover" function is working, i mean it's detecting when the cursor (i mean where the player aim) is in the button.


I can't find gmod's original function which call DoClick so i can't really compare both.

I really hope it will be fixed

**Comment by HandsomeMatt** [comment]
you're probably better off asking on FP sorry, I don't even have gmod installed currently - will leave the issue open though since it is a bug.

**Comment by ExtReMLapin** [comment]
I'm banned from FP, but tbh i just used a DPanel so it's okay.

**Comment by axelbm** [comment]
I fix this bug :)

**Comment by HandsomeMatt** [comment]
Fixed in #13
